name: 获取JavRate演员数据

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  crawl-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置Python 3.10环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 配置Git用户信息
        run: |
          git config user.name "GitHub Actions Crawler"
          git config user.email "actions-crawler@github.com"

      - name: 运行爬虫脚本
        run: python Widgets/javrate_actor_crawler.py

      - name: 检查数据文件是否生成
        id: check_file
        run: |
          if [ -f "Widgets/javrate_actors.json" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: 提交并推送数据文件
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          git add Widgets/javrate_actors.json
          git commit -m "自动更新: JavRate演员数据"
          git push
          echo "数据文件已成功提交到仓库"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
